#!/usr/bin/env bash
# xdotool key ctrl+l
# sleep .5
echo """await \\
   'dig +short facebook.com'   \\
   'nslookup apple.com'        \\
   'whois amazon.com'          \\
   'sleep 1 | telnet netflix.com 443 2>/dev/null' \\
   'http google.com'
""" | xclip
clear
fish
sleep 1
xdotool key shift+Insert
sleep 10
