# Generated by scripts/homebrew-formula.sh from the 2.10.0 release's SHA256SUMS.
# Don't edit by hand: the release job regenerates it on every push to main.
class Await < Formula
  desc "Runs commands in parallel and waits for their termination"
  homepage "https://github.com/slavaGanzin/await"
  version "2.10.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/slavaGanzin/await/releases/download/2.10.0/await-2.10.0-aarch64-apple-darwin.tar.gz"
      sha256 "6e5976b4b851eb04aa006acc425658a595401613defe477ea87e26f1d8f24a04"
    end
    on_intel do
      url "https://github.com/slavaGanzin/await/releases/download/2.10.0/await-2.10.0-x86_64-apple-darwin.tar.gz"
      sha256 "54c7adf278a6d6f143525e51eda5443e27978055f255019bdab9e0ece7e0e027"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/slavaGanzin/await/releases/download/2.10.0/await-2.10.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "c772ebcd78c39536e32e174291f85c5eb3c165c82b8a32c67cae3189f4554699"
    end
    on_intel do
      url "https://github.com/slavaGanzin/await/releases/download/2.10.0/await-2.10.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "3ab1f0aebfdd28e5ec6188b72323565e9880ced262501be4001c983a5db9c5d9"
    end
  end

  def install
    bin.install "await"
    bash_completion.install "await.bash" => "await"
    fish_completion.install "await.fish"
    # await.zsh is meant to be sourced (it runs compinit and compdef itself);
    # turn it into an autoloadable _await for site-functions
    zsh = File.readlines("await.zsh").grep_v(/^\s*(autoload -Uz compinit|compinit|compdef )/).join
    (zsh_completion/"_await").write "#compdef await\n#{zsh}\n_await \"$@\"\n"
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/await --version").strip
  end
end
