# Generated by scripts/homebrew-formula.sh from the 2.11.0 release's SHA256SUMS.
# Don't edit by hand: the release job regenerates it on every push to main.
class Await < Formula
  desc "Runs commands in parallel and waits for their termination"
  homepage "https://github.com/slavaGanzin/await"
  version "2.11.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/slavaGanzin/await/releases/download/2.11.0/await-2.11.0-aarch64-apple-darwin.tar.gz"
      sha256 "c9d7de087e4b521ef37e09c3089b22084ebd81e371f9aab868b90d1ad628c5c4"
    end
    on_intel do
      url "https://github.com/slavaGanzin/await/releases/download/2.11.0/await-2.11.0-x86_64-apple-darwin.tar.gz"
      sha256 "21c51164c9017a9033793542d54d3fc0a67668a95ac2faaa347149be7f0bdc7f"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/slavaGanzin/await/releases/download/2.11.0/await-2.11.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "7e4f4348ab4e17db0e2fd4122618902e36c2e11752e4487cbf982ac5f0f7a1e6"
    end
    on_intel do
      url "https://github.com/slavaGanzin/await/releases/download/2.11.0/await-2.11.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "b6c02cb43f76a7f4f93e19379bbf0ca9a5d4d8ca0fbab73f302878b123b6086f"
    end
  end

  def install
    bin.install "await"
    bash_completion.install "await.bash" => "await"
    fish_completion.install "await.fish"
    # the man page ships in archives from 2.11.0 on
    man1.install "await.1" if File.exist?("await.1")
    # await.zsh is meant to be sourced (it runs compinit and compdef itself);
    # turn it into an autoloadable _await for site-functions
    zsh = File.readlines("await.zsh").grep_v(/^\s*(autoload -Uz compinit|compinit|compdef )/).join
    (zsh_completion/"_await").write "#compdef await\n#{zsh}\n_await \"$@\"\n"
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/await --version").strip
  end
end
