#!/usr/bin/env bash
./build
echo """# await
*runs list of commands and waits for their termination*

### Examples
#### Healthcheck FAANG
<img src='demo1.gif' width='100%'/>


## Installation
\`\`\`bash
curl https://github.com/slavaGanzin/await/releases/tag/0.9/await -o /usr/local/bin/await
\`\`\`

## --help
\`\`\`bash
$(./await --help)

\`\`\`
""" > README.md
git add README.md
cp await /usr/local/bin/await
