#!/usr/bin/env bash
gcc await.c -o await
echo """# await
*runs list of commands and waits for their termination*

### Examples
#### Healthcheck FAANG
![](demo1.gif)


## Installation
\`\`\`bash
curl https://github.com/slavaGanzin/await/releases/tag/0.9/await -o /usr/local/bin/await
\`\`\`

## --help
\`\`\`bash
$(./await --help)

\`\`\`
""" > README.md
git add .
