#!/usr/bin/env bash
# Generate the Homebrew formula (Formula/await.rb) for a published release.
#
#   scripts/homebrew-formula.sh <version> <SHA256SUMS> [output]   (output defaults to Formula/await.rb)
#   scripts/homebrew-formula.sh --check <SHA256SUMS> [formula]
#     exits 1 (naming each mismatch) unless every url/sha256 pin in the
#     formula matches SHA256SUMS
#
# The formula installs the prebuilt release archives, pinned by the checksums in
# that release's SHA256SUMS. The release job runs this after every upload (the
# archives, and so their checksums, change on every push to main), so don't edit
# Formula/await.rb by hand.
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"

if [ "${1:-}" = --check ]; then
  [ $# -ge 2 ] && [ $# -le 3 ] || { echo "usage: $0 --check <SHA256SUMS> [formula]" >&2; exit 2; }
  sums=$2
  formula=${3:-"$root/Formula/await.rb"}
  [ -r "$sums" ] || { echo "can't read $sums" >&2; exit 2; }
  [ -r "$formula" ] || { echo "can't read $formula" >&2; exit 2; }
  # every url must be followed by the sha256 that SHA256SUMS lists for that archive
  awk -v formula="$formula" '
    NR == FNR { if (length($1) == 64) { f = $2; sub(/^\*/, "", f); live[f] = $1 }; next }
    /^[ \t]*url "/ { u = $0; sub(/^[ \t]*url "/, "", u); sub(/".*/, "", u); n = split(u, p, "/"); file = p[n]; next }
    /^[ \t]*sha256 "/ && file != "" {
      h = $0; sub(/^[ \t]*sha256 "/, "", h); sub(/".*/, "", h); pairs++
      if (!(file in live)) { print formula ": " file " is not in SHA256SUMS"; bad++ }
      else if (live[file] != h) { print formula ": " file " pins " h ", SHA256SUMS has " live[file]; bad++ }
      file = ""
    }
    END {
      if (pairs < 4) { print formula ": expected 4 url/sha256 pairs, found " pairs + 0; bad++ }
      if (bad) exit 1
      print formula ": all " pairs " url/sha256 pairs match SHA256SUMS"
    }' "$sums" "$formula"
  exit
fi

if [ $# -lt 2 ] || [ $# -gt 3 ]; then
  echo "usage: $0 <version> <SHA256SUMS> [output]" >&2
  exit 2
fi

version=$1
sums=$2
out=${3:-"$root/Formula/await.rb"}

case $version in
  ''|*[!0-9A-Za-z.+-]*) echo "bad version: $version" >&2; exit 2;;
esac
[ -r "$sums" ] || { echo "can't read $sums" >&2; exit 2; }

base="https://github.com/slavaGanzin/await/releases/download/$version"

sha() {
  local file="await-$version-$1.tar.gz" s
  s=$(awk -v f="$file" '($2 == f || $2 == "*" f) && $1 ~ /^[0-9a-f]+$/ && length($1) == 64 {print $1; exit}' "$sums")
  [ -n "$s" ] || { echo "$file is not in $sums" >&2; exit 1; }
  printf '%s' "$s"
}

mac_arm=$(sha aarch64-apple-darwin)
mac_intel=$(sha x86_64-apple-darwin)
linux_arm=$(sha aarch64-unknown-linux-musl)
linux_intel=$(sha x86_64-unknown-linux-musl)

mkdir -p "$(dirname "$out")"
tmp="$out.tmp.$$"
cat > "$tmp" <<RUBY
# Generated by scripts/homebrew-formula.sh from the $version release's SHA256SUMS.
# Don't edit by hand: the release job regenerates it on every push to main.
class Await < Formula
  desc "Runs commands in parallel and waits for their termination"
  homepage "https://github.com/slavaGanzin/await"
  version "$version"
  license "MIT"

  on_macos do
    on_arm do
      url "$base/await-$version-aarch64-apple-darwin.tar.gz"
      sha256 "$mac_arm"
    end
    on_intel do
      url "$base/await-$version-x86_64-apple-darwin.tar.gz"
      sha256 "$mac_intel"
    end
  end

  on_linux do
    on_arm do
      url "$base/await-$version-aarch64-unknown-linux-musl.tar.gz"
      sha256 "$linux_arm"
    end
    on_intel do
      url "$base/await-$version-x86_64-unknown-linux-musl.tar.gz"
      sha256 "$linux_intel"
    end
  end

  def install
    bin.install "await"
    bash_completion.install "await.bash" => "await"
    fish_completion.install "await.fish"
    # await.zsh is meant to be sourced (it runs compinit and compdef itself);
    # turn it into an autoloadable _await for site-functions
    zsh = File.readlines("await.zsh").grep_v(/^\\s*(autoload -Uz compinit|compinit|compdef )/).join
    (zsh_completion/"_await").write "#compdef await\\n#{zsh}\\n_await \\"\$@\\"\\n"
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/await --version").strip
  end
end
RUBY
mv "$tmp" "$out"
echo "wrote $out ($version)"
