name: build and run tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: compile
      run: cc await.c -o await
    - name: Upload Example binary
      uses: actions/upload-artifact@v1
      with:
        name: upload binary
        path: build/src/Example
